### PR TITLE
[GROOVY-9109] GroovyShell: don't override classloader if parent is al…

### PR DESCRIPTION
**Pull request by je-ik**
…ready GroovyClassLoader

### CODE REVIEW

**Comment by je-ik** [comment]
@paulk-asert Would it be possible merge this for the upcoming release of 3.0.0-beta-2?

**Comment by je-ik** [comment]
@paulk-asert @danielsun1106 can we get this into upcoming 2.5.8 release, please?

**Comment by danielsun1106** [comment]
We will merge PRs into branches, so just submit PRs to master ;-)

**Comment by je-ik** [comment]
Okay, understood. Closing this.

**Pull request closed without merging**
