### PR TITLE
Remove need for compiler config from parser creation

### PR DESCRIPTION
**Pull request by eric-milles**

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

The following changes will have to be reverted because antlr2 parser will be removed since 4.0.0. /cc @paulk-asert 
https://github.com/apache/groovy/pull/1149/files#diff-7b973e8bb30f308ec7d1427173b9abb0L36-R48

**Comment by paulk-asert** [comment]
It's on the roadmap to remove antlr2 for 4 as well as the non-indy bytecode generation. There are a bunch of legacy classes, e.g. Java2Groovy and SourcePrinter which we haven't replaced yet hence why it hasn't been axed just yet.

**Comment by eric-milles** [comment]
Is this roadmap available for public viewing.

**Comment by paulk-asert** [comment]
We need to get better at capturing roadmap. I'll send an email to dev mailing list.

**Comment by danielsun1106** [comment]
Merged. Thanks.
As for removing the old parser in Groovy 4.0.0, let's remove the related code totally.

**Pull request merged**
