### PR TITLE
upgrade ASM from 6.1.1 to 7.2 to fix https://issues.apache.org/jira/browse/GROOVY-9271

### PR DESCRIPTION
**Pull request by ispringer**

### CODE REVIEW

**Comment by eric-milles** [comment]
Is this change specific to Groovy 2.4?  Groovy 2.5 only has ASM 7.1.

**Comment by ispringer** [comment]
If 2.5 is already using ASM 7.1, then the bug is likely specific to 2.4, since the ASM bug was fixed in ASM 7.1 (see https://asm.ow2.io/versions.html). My colleague verified that 7.1 fixes the Groovy issue as well. Would you like me to switch the PR from 7.2 to 7.1 for consistency with the 2.5 branch?

**Comment by eric-milles** [comment]
Yes, 7.1 to be aligned with Groovy 2.5 would be my suggestion.

**Comment by eric-milles** [comment]
@danielsun1106 Do you see any issue with this change?  Is there any reason Groovy 2.4 uses ASM 6 and Groovy 2.5 uses ASM 7 besides time?

@paulk-asert Is there a possibility of a minor Groovy 2.4 release for this and other small bug fixes?

**Comment by eric-milles** [comment]
@danielsun1106 Do you see any issue with this change?  Is there any reason Groovy 2.4 uses ASM 6 and Groovy 2.5 uses ASM 7 besides time?

@paulk-asert Is there a possibility of a minor Groovy 2.4 release for this and other small bug fixes?

**Comment by danielsun1106** [comment]
It's OK to bump asm to 7.X, but it is a big bump, so we are not sure whether it will impact existing projects. Also, 2_4_X is not maintained any more unless some blocker issues are found.

**Comment by ispringer** [comment]
This is a blocker issue for us, as far as being able to upgrade to 2.4.16 or 2.4.17, to get the bug fixes in those releases, particularly 2.4.16 which has several bug fixes for issues we have experienced. We are currently using an internal fork of 2.4.17 in production, which we obviously like to avoid.

**Comment by paulk-asert** [comment]
@eric-milles We didn't plan on another 2.4.x release but if this is a blocker for some, we can certainly do one.

**Comment by eric-milles** [comment]
@paulk-asert Can this be merged as-is or with ASM 7.2?  I ran the build locally on the 2.4 branch and there were no failures.  I'm not sure if there were any changes required or problems when Groovy 2.5+ was moved to ASM 7+.

**Comment by paulk-asert** [comment]
You can close this. The Groovy 2.5 branch is already using 7.2.

**Comment by paulk-asert** [comment]
You can close this since ASM has been changed to 7.2 on the 2_4_X branch. If we do another release, it will contain the fix.

**Comment by ispringer** [comment]
Hi @paulk-asert, did you send an email to the dev list regarding a 2.4.18 release?

**Comment by paulk-asert** [comment]
@ispringer There has already been a 2.4.18 release, so we would be talking about a 2.4.19 that could contain this change. It would have been nice to have included this change into the codebase prior to the 2.4.18 release but we didn't have the cycles to do all the needed testing prior to now (we typically do some manually testing with numerous projects in addition to the normal test suite). There has been no discussion about a 2.4.19 release as yet.

**Comment by eric-milles** [comment]
https://github.com/apache/groovy/commit/5d6c43ffae75307933815a706d6b6451c5376144

**Pull request closed without merging**
