### PR TITLE
Newify pattern support for pull

### PR DESCRIPTION
**Pull request by mgroovy**
Clean commit from force rebased Groovy trunk for pull request

### CODE REVIEW

**Comment by danielsun1106** [comment]
Nice.
Could you please create a JIRA issue to track the PR?

**Comment by mgroovy** [comment]
https://issues.apache.org/jira/browse/GROOVY-8490

**Comment by danielsun1106** [comment]
Merged. Thanks! 
Looking forward to a JIRA issue to track it :-)

**Comment by mgroovy** [comment]
@danielsun1106 Jira issue: Do you mean something other than GROOVY-8490 ?-)

**Comment by danielsun1106** [comment]
GROOVY-8490 is what I am looking for. Thanks ;-)

**Comment by mgroovy** [comment]
OK, thanks for merging so quickly :-)

**Comment by danielsun1106** [comment]
2.5.0 RC-2 is coming soon, we must catch the train ;-)

**Comment by mgroovy** [comment]
@2.5.0 RC-2: Agreed :-)

**Pull request closed without merging**
