### PR TITLE
Resource leaks in Groovyc

### PR DESCRIPTION
**Pull request by Persi**
Building multiple ant projects in a row within the same JVM sometimes fails on windows with locked jars. This is e.g. the case if two build projects has circle dependencies.

### CODE REVIEW

**Comment by jwagenleitner** [comment]
Does https://issues.apache.org/jira/browse/GROOVY-7573 look related?  Also, just for future reference it's probably best to do the PR against master.

**Comment by Persi** [comment]
Hello @jwagenleitner, thanks for your link. This sounds absolutely like our error case.
I know that pushing against master is preferred, but in this case I wanted to bring the change live a little bit earlier, as Groovy 2.6 will release way later than 2.5.

Thanks for your advice.

**Comment by danielsun1106** [comment]
@Persi 
FYI, normally we merge PRs into master and back-port them to other branches ;)

**Comment by Persi** [comment]
@danielsun1106 so do I have to merge the changes to 2.6 Branch and create a new PR or is it OK to merge to 2.5? Because I don't want to break your rules ;)

**Comment by danielsun1106** [comment]
@Persi Thanks for your contribution. Would you mind creating a new PR to merge into master and closing this one?

**Comment by Persi** [comment]
Merging in Master is preferred, so I'll merge to master and create new PR.

**Pull request closed without merging**
