### PR TITLE
GROOVY-9316: Improved toString for AnnotationNode

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

**Comment by eric-milles** [comment]
Is there a before and after string for comparison?

**Comment by paulk-asert** [comment]
Before is normal Object toString, e.g.:
`org.codehaus.groovy.ast.AnnotationNode@e8ff0`
After is:
`org.codehaus.groovy.ast.AnnotationNode@e8ff0[@Deprecated(since: 3.0.0, forRemoval: true)]`

**Comment by eric-milles** [comment]
Thanks.  Could that be indicated in the issue since most people are not going to dig into the PR ?

**Comment by paulk-asert** [comment]
Done. Nice suggestion.

**Pull request closed without merging**
