### PR TITLE
GROOVY-9964: Groovy 3 compilation is much slower than Groovy 2 compil…

### PR DESCRIPTION
**Pull request by danielsun1106**
…ation for Gradle build scripts

### CODE REVIEW

**Comment by eric-milles** [comment]
Are there any performance measurements for this change?  Nothing is mentioned in the linked issue about what is taking the time or how much improvement to expect.

**Comment by danielsun1106** [comment]
I tested with "project0/build.gradle" file  locally, about 10% time saved.
As for the goal, tune the performance as good as we could...

**Comment by paulk-asert** [comment]
So, we have to eliminate the lambda chaining to gain the performance? I.e. GROOVY-8991 would be broken?

**Comment by danielsun1106** [comment]
It is not expected... but parser suffers from ambiguities while choosing alternatives... Maybe we have to find better way to improve the parsing performance...

**Pull request closed without merging**
