### PR TITLE
GROOVY-6360: GString performance is slow with String's trim method

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by paulk-asert** [comment]
This avoids using reflection for two common String methods and, for Groovy 4, will piggy back on the already implemented improved caching.

**Comment by danielsun1106** [comment]
How about adding all methods of String to GStringImpl, e.g. substring, indexOf, lastIndexOf, etc.

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Comment by vy** [comment]
Hello, I have two questions regarding this PR:

1. Does this help with `StringBuilder#append(GString)`?
2. Will this be backported to 3.x?

**Pull request merged**
