### PR TITLE
GROOVY-8805 reloading a script under GroovyScriptEngine should succee…

### PR DESCRIPTION
**Pull request by gclayburg**
…d when dependent class is deleted

### CODE REVIEW

**Comment by danielsun1106** [comment]
LGTM. Thanks for your contribution.

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Comment by danielsun1106** [comment]
As the PR is not binary compatible, so it will be merged into master, i.e. groovy 3

**Comment by gclayburg** [comment]
ok cool.  I wasn't really sure which branch I should be working with.  I just chose the one I did based on the version I was using, i.e 2.5.x

**Pull request closed without merging**
