### PR TITLE
GROOVY-9083: groovyConsole should be updated to understand method ref…

### PR DESCRIPTION
**Pull request by paulk-asert**
…erences and lambda expressions

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

**Comment by mvmn** [comment]
Why doesn't this work in Groovy Shell though?

```
> [1,2,3].stream().map(String::valueOf).collect(java.util.stream.Collectors.toList())
groovysh_parse: 2: unexpected token: : @ line 2, column 29.
   [1,2,3].stream().map(String::valueOf).collect(java.util.stream.Collectors.toList())
                               ^
> [1,2,3].stream().map(v->String.valueOf(v)).collect(java.util.stream.Collectors.toList())
groovysh_parse: 2: unexpected token: -> @ line 2, column 23.
   [1,2,3].stream().map(v->String.valueOf(v)).collect(java.util.stream.Collectors.toList())
                         ^
```

**Comment by danielsun1106** [comment]
@mvmn groovysh does not support new language features because it still bases on the old parser.

**Comment by paulk-asert** [comment]
Our goal is to get as many of the tools ported across to the new parser before 3.0 GA but some may have to wait until a subsequent (e.g. 3.0.x or 3.1) release.

**Pull request merged**
