### PR TITLE
GROOVY-7443: traits classloaders support

### PR DESCRIPTION
**Pull request by dkobylarz**
GROOVY-7443: traits classloaders support

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@blackdrag Is the good to merge?

**Comment by dkobylarz** [comment]
it's been squashed into a single commit, please review it

**Comment by PascalSchumacher** [comment]
@dkobylarz Sorry for the late feedback. Can you please merge the double blank lines into single blank lines? Also the pull it should contain a testcase, e.g the one from the Jira issue.

Thanks!

**Comment by paulk-asert** [comment]
The relevant commit was merged - the others were ignored. Thanks.

**Pull request closed without merging**
