### PR TITLE
GROOVY-9675: There should be a mechanism to disable individual macro …

### PR DESCRIPTION
**Pull request by paulk-asert**
…methods & extension methods

### CODE REVIEW

**Comment by paulk-asert** [comment]
Since checking individual methods could have a performance impact, I have used a single system property to turn on the disabling feature. E.g.
```
-Dgroovy.macro.disable=true    // turn on globally
-Dgroovy.macro.disable.foo=true  // disable the 'foo' macro (any macro with that name)

-Dgroovy.extension.disable=true    // turn on globally
-Dgroovy.extension.disable.dump=true  // disable the 'dump' extension method (any with that name)

```

**Comment by eric-milles** [comment]
Is there ever a reason to set one of these properties to true?  Instead how about one property that is set the the name(s) of the disabled macros or extensions?  Like, `-Dgroovy.macro.disable=*` or `-Dgroovy.macro.disable=foo,bar` or a pattern that could be compiled once and matched against the names.

Will it be possible to disable macros or extensions using compiler configuration?  Or is this just a system property mechanism?  IMO there are too many special system property controls/switches.

If I want to disable just one instance of `each` or `getAt` (for example) is that possible or must it be all or none?

**Comment by paulk-asert** [comment]
We could probably do the `-Dgroovy.macro.disable=foo,bar` variant. We want something that is going to be fast, so I'd avoid Patterns.

A compiler configuration option isn't enough - it doesn't cover dynamic Groovy and I think it might be a little messy trying to block off access to extensions/macros once they are in our caches. Good news though for @CompileStatic code is that you only need the switch during compilation.

We could get fancier trying to disable particular variants of extensions/macros but I felt YAGNI calling. I imagine disabling would mostly be for folks already using methods with those names when new macros are introduced. They'd just want to block all variants and perhaps consider refactoring and removing the disable switch later.

**Comment by paulk-asert** [comment]
@eric-milles adjusted as per your suggestion

**Comment by danielsun1106** [comment]
Merged. Thanks.

**Pull request merged**
