### PR TITLE
Test on JDK 22 and update JDK 23 EA

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by Goooler** [comment]
Ooops, this may need Gradle 8.8

**Comment by daniellansun** [comment]
Gradle 8.7 does not support JDK 22 because it still uses Groovy 3.

**Comment by paulk-asert** [comment]
> Gradle 8.7 does not support JDK 22 because it still uses Groovy 3.

Gradle 8.7 uses Groovy 3.0.17. Groovy 3.0.21 embeds ASM 9.6 and hence can read JDK 22 class files. We have additional support for recent JDKs in Groovy 4+. We haven't done any testing to try to determine whether Gradle needs the additional support or is unaffected.

**Comment by Goooler** [comment]
@paulk-asert PTL

**Pull request merged**
