### PR TITLE
Simplify MacroGroovy substitutions' implementation.

### PR DESCRIPTION
**Pull request by bsideup**
Assume the order of substitutions, so we can use a list instead of a map to pass the context. 

Fixes some Antlr4 migration-related issues ( https://github.com/danielsun1106/groovy/issues/5 )

/cc @melix

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

**Comment by paulk-asert** [comment]
+1, looks good to me

**Comment by bsideup** [comment]
@paulk-asert so far, the only issue I see is the order change. It potentially might happen if we change the visitors, but I have no idea how to force the order. Is it safe to rely on the order of visit right now? Is it depth-first search?

**Comment by danielsun1106** [comment]
Any problem prevents the PR from merging?

**Comment by paulk-asert** [comment]
I was just going to play a little more with ordering ...

**Comment by danielsun1106** [comment]
@paulk-asert 
Paul, any problem on the ordering?

**Comment by bsideup** [comment]
@paulk-asert ping :)

**Comment by paulk-asert** [comment]
Sorry, it's about 4 or 5th on my todo list to look at. Hopefully next week.

**Comment by bsideup** [comment]
@paulk-asert ok, sure, just pinging :)

**Comment by danielsun1106** [comment]
@paulk-asert ping ;)

**Comment by danielsun1106** [comment]
I've merge the PR into the `parrot` branch manually. Everything is OK. 

@bsideup 
Thank you, Sergei :)

**Comment by paulk-asert** [comment]
I did a bit more testing and couldn't break it so far. I'll merge shortly.

**Pull request closed without merging**
