### PR TITLE
GROOVY-9505: Bump ASM_API_VERSION to Opcodes.ASM8

### PR DESCRIPTION
**Pull request by KamilJedrzejuk**
Related with issue:
https://issues.apache.org/jira/browse/GROOVY-9505
https://github.com/spockframework/spock/issues/1142#issuecomment-612855754

### CODE REVIEW

**Comment by KamilJedrzejuk** [comment]
image

**Comment by szpak** [comment]
It seems to be a random error on a dependency downloading. Try:
```
git commit --amend
git push --force-with-lease
```
to re-trigger the build.

**Comment by szpak** [comment]
You may also rebase your commit into one, along the way.

**Comment by KamilJedrzejuk** [comment]
image

**Comment by KamilJedrzejuk** [comment]
Can anyone help me?

**Comment by danielsun1106** [comment]
@KamilJedrzejuk no worries, I'll deal with your PR at this weekend ;-)

**Comment by paulk-asert** [comment]
Merged, thanks!

**Comment by KamilJedrzejuk** [comment]
Does current version support jdk14?

**Comment by paulk-asert** [comment]
@KamilJedrzejuk Yes, fixed in 3.0.4. You always check the fix version by clicking through to the relevant issue, e.g. GROOVY-9505.

**Pull request closed without merging**
