### PR TITLE
GROOVY-5744, GROOVY-10666: multi-assign via `iterator()` or `getAt(int)`

### PR DESCRIPTION
**Pull request by eric-milles**
Support multi-assign for `Stream` and `Iterator`.  Improve efficiency of multi-assign for types that do not support direct indexing like `Set`.

Translate "def (one,two) = rhs" into (pseudo-code):
```groovy
def one, two;
{
  def iter = rhs.iterator(), first;
  if (iter.hasNext() && (first = iter.next()) !== rhs) {
    one = first
    two = iter.hasNext() ? iter.next() : null
  } else {
    one = rhs.getAt(0)
    two = rhs.getAt(1)
  }
}
```

https://issues.apache.org/jira/browse/GROOVY-10666
https://issues.apache.org/jira/browse/GROOVY-5744

### CODE REVIEW

**Comment by blackdrag** [comment]
I don't see changes from double quotes to single quotes as formatting change, nor do I see a change from {} to {->} as such a change. So where any of these changes required for this code change to pass?

**Comment by paulk-asert** [comment]
On my list to look at tomorrow.

**Comment by daniellansun** [comment]
Merged. Thanks.

**Comment by paulk-asert** [comment]
I'll probably revert this, I have an alternative implementation which I have spoken to Eric about but I have been too busy with ApacheCon to get my PR ready for review.

**Comment by daniellansun** [comment]
Got it.

**Comment by eric-milles** [comment]
@paulk-asert Instead of revert, can you just replace the "multiple declaration or assignment" block?  There are some other fixups, including new test cases that I'd like to keep.

**Comment by paulk-asert** [comment]
@eric-milles I'll see what I can do.

**Pull request merged**
