### PR TITLE
GROOVY-6352 Check the arguments even for the default constructor

### PR DESCRIPTION
**Pull request by fpavageau**

### CODE REVIEW

**Comment by blackdrag** [comment]
+1

**Comment by fpavageau** [comment]
As requested by @melix in his [comment](3522575#commitcomment-15101645), I added an explicit test for the array case, even if it was already covered by the tests in `ArraysAndCollectionsSTCTest`.

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Comment by PascalSchumacher** [comment]
https://github.com/apache/groovy/commit/5c8d97b2cade37a8d4c7c21ecb94d6d35e9e15a8 is the commit. I forgot to amend the commit, so that the pull request is automatically closed. Could you please close the pull request manually? (I can not do, because this is a read only repo.)

**Comment by fpavageau** [comment]
Sure, thanks for merging.

**Pull request closed without merging**
