### PR TITLE
CompilerConfiguration.output doesn't seem to be used for anything

### PR DESCRIPTION
**Pull request by yaccz**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@blackdrag @melix What do you think, should we merge this?

**Comment by blackdrag** [comment]
The change is not a binary compatible one... I guess the error reporter should have used that output to print the error messages to. So we can remove the property, but not in 2.4. And frankly, for 2.5 I think it should be deprecated only

**Comment by yaccz** [comment]
@PascalSchumacher done.

**Comment by PascalSchumacher** [comment]
Thanks!

**Pull request closed without merging**
