### PR TITLE
Make json output configurable to not write entries with null values

### PR DESCRIPTION
**Pull request by MarcusJL**
Hi I would like to propose a simple solution for GROOVY-7858 / GROOVY-7780.

This is providing overriding methods with a boolean flag to skip writing entries with null values for Closure Map and Expando. 

If there are plans to have a more sophisticated solution e.g using some more general configuration I would be glad to support on that.

### CODE REVIEW

**Comment by graemerocher** [comment]
This seems related to https://github.com/apache/groovy/pull/371

**Comment by paulk-asert** [comment]
I am probably -1 on this proposal assuming that #371 is merged.
It seems to cover all the cases fairly well:
```
import groovy.json.*

def Closure closureWithNullValues = {
  optionalValue null
  constantValue 37
}

def json1 = new JsonBuilder(closureWithNullValues)
assert json1.toString() == '{"optionalValue":null,"constantValue":37}'

def options = JsonOutput.options().excludeNulls()
def json2 = new JsonBuilder(closureWithNullValues, options)
assert json2.toString() == '{"constantValue":37}'

def generator = JsonOutput.options().excludeNulls().createGenerator()
assert generator.toJson(json1.content) == '{"constantValue":37}'

def Expando expandoWithNullValues = new Expando(optionalValue: null, constantValue: 37)
assert generator.toJson(expandoWithNullValues) == '{"constantValue":37}'

TreeMap<String, Integer> mapWithNullValues = [constantValue:37,optionalValue:null]
assert generator.toJson(mapWithNullValues) == '{"constantValue":37}'
```
Perhaps not as cleanly as with a single boolean flag, but in a more general way.

**Comment by jwagenleitner** [comment]
@MarcusJL if you have any feedback on #371 I'd be interested to know since you have looked at this problem.

**Comment by MarcusJL** [comment]
I agree #371 will solve this issue in a more generic way. Can be closed if #371 is merged.

**Pull request closed without merging**
