### PR TITLE
GROOVY-7569: Use verbose formatting for PowerAsserts

### PR DESCRIPTION
**Pull request by tkruse**
See JIRA for more explanation. (https://issues.apache.org/jira/browse/GROOVY-7569)

This was based on the recently merged GROOVY-7563, so not sure if can be backported without those other commits.

### CODE REVIEW

**Comment by danielsun1106** [comment]
@paulk-asert The PR looks good. How about merging it?
P.S. It seems that I have not privilege to merge PR.

**Comment by paulk-asert** [comment]
Merging isn't done through the github interface - that's an Apache workflow "feature". Instead just manually merge and amend (one of) the commit(s) to include wording like: "(closes #374)".

**Comment by paulk-asert** [comment]
I'll merge it after running some checks.

**Comment by paulk-asert** [comment]
Applied. Thanks. (Not backported to 2_4_X)

**Comment by PascalSchumacher** [comment]
Great pull request. :+1: Really sad it too so long to be merged.

**Comment by tkruse** [comment]
thanks. I actually had forgotten about it.

**Pull request closed without merging**
