### PR TITLE
GROOVY-9236: Avoid unnecessary resolving

### PR DESCRIPTION
**Pull request by danielsun1106**

### CODE REVIEW

**Comment by danielsun1106** [comment]
The PR is ready to be reviewed.
Ping @paulk-asert ;-)

**Comment by danielsun1106** [comment]
The following lists show the difference caused by the PR.

* After changes:
```
groovy.lang.GroovyObject$java$util$stream$Collectors
groovy.lang.GroovyObject$groovy$transform$CompileStatic
groovy.lang.GroovyObject$java$util$stream$Stream
groovy.lang.GroovyObject$CompileStatic
groovy.lang.GroovyObject$Collectors
Script1BeanInfo
Script1Customizer
Script1$_p_lambda1BeanInfo
Script1$_p_lambda1Customizer
```

* Before changes:
```
Script1$_p_lambda1BeanInfo
Script1$_p_lambda1Customizer
Script1BeanInfo
Script1Customizer
groovy$transform$CompileStatic
groovy.lang.GroovyObject$Collectors
groovy.lang.GroovyObject$CompileStatic
groovy.lang.GroovyObject$groovy$transform$CompileStatic
groovy.lang.GroovyObject$java$util$stream$Collectors
groovy.lang.GroovyObject$java$util$stream$Stream
groovy.lang.groovy$transform$CompileStatic
groovy.lang.java$util$stream$Collectors
groovy.lang.java$util$stream$Stream
groovy.transform$CompileStatic
groovy.util.groovy$transform$CompileStatic
groovy.util.java$util$stream$Collectors
groovy.util.java$util$stream$Stream
java$util$stream$Collectors
java$util$stream$Stream
java.io.groovy$transform$CompileStatic
java.io.java$util$stream$Collectors
java.io.java$util$stream$Stream
java.lang.groovy$transform$CompileStatic
java.lang.java$util$stream$Collectors
java.lang.java$util$stream$Stream
java.net.groovy$transform$CompileStatic
java.net.java$util$stream$Collectors
java.net.java$util$stream$Stream
java.util$stream$Collectors
java.util$stream$Stream
java.util.groovy$transform$CompileStatic
java.util.java$util$stream$Collectors
java.util.java$util$stream$Stream
java.util.stream$Collectors
java.util.stream$Stream
```

**Comment by danielsun1106** [comment]
@blackdrag 
Jochen, if you could set aside some time to review the PR too, that would be great :-)

**Comment by danielsun1106** [comment]
As `resolveToOuter` only resolves classes whose name does not contains `.` and `resolveFromStaticInnerClasses` only resolves classes whose name contains `.`, no overlap in their target classes to resolve, thus no breaking changes in the PR IMO.

https://github.com/apache/groovy/blob/79dfd8586b33e3c80add6b2ffb26c07ff7a6e8b3/src/main/java/org/codehaus/groovy/control/ResolveVisitor.java#L845-L856

https://github.com/apache/groovy/blob/79dfd8586b33e3c80add6b2ffb26c07ff7a6e8b3/src/main/java/org/codehaus/groovy/control/ResolveVisitor.java#L552-L558

**Comment by blackdrag** [comment]
could you first show what you compiled with that? And I think we will need more cases to for review. At the very least I would like to see the class that was resolved in the end.

**Comment by danielsun1106** [comment]
I tried to compile the following code to verify whether the times of guessing class names are reduced.
```
                import groovy.transform.CompileStatic
                import java.util.stream.Collectors
                import java.util.stream.Stream
                
                @CompileStatic
                void p() {
                    assert [2, 3, 4] == [1, 2, 3].stream().map(e -> e.plus 1).collect(Collectors.toList())
                }
                
                p()
```

**Comment by blackdrag** [comment]
your change looks like progress no doubt, but why is there still "groovy.lang.GroovyObject$groovy$transform$CompileStatic" in there? ideally "import groovy.transform.CompileStatic" would cause a lookup to "groovy.transform.CompileStatic" and then it is done. And then what is Script1Customizer again for? And then the BeanInfo.. I think those two are specific to static compilation, right?

**Comment by danielsun1106** [comment]
As we can see, STC is enabled by `@CompileStatic`.
`groovy.lang.GroovyObject$groovy$transform$CompileStatic` is guessed by `resolveNestedClasses`, which has highest precedence of resolving. As for `Script1BeanInfo` and `Script1Customizer`, they will be looked up too before the changes of the PR... Frankly, I do not know where they come from for now...

https://github.com/apache/groovy/blob/6e387d09b00663faccb8390a027e7e4d23a7a011/src/test/groovy/bugs/groovy9236/Groovy9236Bug.groovy#L64

**Comment by danielsun1106** [comment]
@melix 
Hi Cédric, I am trying to reducing the cost of resolving[1], could you review the PR too? Thanks in advance :-)

[1] http://groovy.329449.n5.nabble.com/Performance-of-the-compiler-tt5750989.html

**Comment by danielsun1106** [comment]
@paulk-asert 
In theory, it is not a breaking chang and its build is green. But we can not test all frameworks based on Groovy, so how about merge the PR for the time being and ask framework maintainers to give it a try? I think it conforms to the meaning of beta releases.

**Comment by paulk-asert** [comment]
Go ahead and commit. I still want to do more testing but won't get time until next week. We can revert/tweak later if we really need to.

**Comment by danielsun1106** [comment]
> We can revert/tweak later if we really need to.
I think so too :-)

**Pull request merged**
