### PR TITLE
Improve generic-ClassNode compiler error message

### PR DESCRIPTION
**Pull request by chrylis**
Explain how (rather than what) should be done to refer to classes with generic types in AST transforms.

GROOVY-10758

### CODE REVIEW

**Comment by chrylis** [comment]
My run of `./gradlew test` had one failing test, but it was in `groovy-ant` and related to a missing XML file, so I don't think that's related to this code change (which is only a string, the contents of which don't appear to be asserted specifically).

**Comment by paulk-asert** [comment]
The other scenario which I think applies sometimes is if you were using ClassHelper.make, you can swap to using ClassHelper.makeWithoutCaching.

**Comment by chrylis** [comment]
@paulk-asert That was what I'd originally tried, but (perhaps due to some other interactions; see GROOVY-10763) it does not resolve the error. Per @eric-milles, the two approaches I outlined are the "official" ones.

**Comment by paulk-asert** [comment]
Merged, thanks!

**Pull request merged**
