### PR TITLE
GROOVY-9067: Compile Java stubs with standard API

### PR DESCRIPTION
**Pull request by danielsun1106**

### CODE REVIEW

**Comment by danielsun1106** [comment]
@paulk-asert @blackdrag 
Please set aside some time to review the PR.

**Comment by blackdrag** [comment]
you are doing more than undoing the change for the in-memory compilation? In general I am partial to in-memory compilation, but it must be done using the normal official API or else it will stop working at one point. Is that not possible?

**Comment by danielsun1106** [comment]
@blackdrag 
Jochen, in-memory compilation is still supported, but in-file compilation is changed to rely on the same API, e.g. `javax.tools.JavaCompiler`. As a result, we can compile all source code in the same way and it will be easier for us to maintain.

**Comment by danielsun1106** [comment]
@blackdrag 
As far as I know, `javax.tools.JavaCompiler` is a normal official API and will not stop working suddenly, isn't it?  :wink:
https://docs.oracle.com/javase/7/docs/api/javax/tools/JavaCompiler.html

**Comment by danielsun1106** [comment]
@blackdrag @paulk-asert 

To sum up, the current implementation supports compiling Java stubs(in-memory and in-file) in the same way via the normal standard API `javax.tools.JavaCompiler`, which can eliminate Jochen's worries. 

If you do not object, I will merge the PR this weekend.

**Comment by paulk-asert** [comment]
I was planning to double check that the ant task wasn't affected by this change but haven't had time yet:
subprojects/groovy-ant/src/main/java/org/codehaus/groovy/ant/GenerateStubsTask.java

**Comment by danielsun1106** [comment]
OK. I will wait you, Paul 😉

**Comment by danielsun1106** [comment]
@paulk-asert 
I find `GenerateStubsTask` is not used any more:
https://github.com/apache/groovy/blob/master/subprojects/groovy-ant/src/main/resources/org/codehaus/groovy/antlib.xml#L26

**Comment by danielsun1106** [comment]
@paulk-asert 
I'm verifying the case you mentioned, i.e. generating stubs with `GenerateStubsTask`:
https://travis-ci.org/danielsun1106/groovy/builds/528064320?utm_source=github_status&utm_medium=notification

**Comment by danielsun1106** [comment]
@paulk-asert 
All tests pass :-)

**Pull request closed without merging**
