### PR TITLE
GROOVY-9464: Made GroovyDoc list inherited properties

### PR DESCRIPTION
**Pull request by moste00**
As per [GROOVY-9464](https://issues.apache.org/jira/browse/GROOVY-9464?jql=project%3DGROOVY%20AND%20id%3DGROOVY-9464 ), groovy doc was made to list inherited properties like inherited fields.

### CODE REVIEW

**Comment by daniellansun** [comment]
Could you add some related tests for the PR?

**Comment by moste00** [comment]
> Could you add some related tests for the PR?

Sorry but under which directory ?

**Comment by daniellansun** [comment]
You could put tests under the following package:

https://github.com/apache/groovy/tree/822b8b413ba1014ec432a3ba0e6a3584fd1b8afb/subprojects/groovy-groovydoc/src/test/groovy/org/codehaus/groovy/tools/groovydoc

**Comment by paulk-asert** [comment]
Merged, thanks! I have just been working on another Groovydoc change, so it won't be too hard for me to add a test.

**Comment by moste00** [comment]
> Merged, thanks! I have just been working on another Groovydoc change, so it won't be too hard for me to add a test.

Hello again, thanks very much! 

Very sorry for not adding the tests in time, I got distracted by a lot of things and only saw the notification just now. Thanks a lot for adding the tests yourself. Cheers.

**Pull request merged**
