### PR TITLE
[GROOVY-9109] GroovyShell: don't override classloader if parent is al…

### PR DESCRIPTION
**Pull request by je-ik**
…ready GroovyClassLoader

### CODE REVIEW

**Comment by paulk-asert** [comment]
The build failure is highlighting the case where the config of the existing groovyclassloader is different to the supplied config.

**Comment by je-ik** [comment]
Oops, thanks @paulk-asert. I didn't notice the fail.

**Comment by paulk-asert** [comment]
That certainly fixed the breaking test. CompilerConfiguration is in general mutable - so being able to get the config allows mutation more readily which isn't ideal. I'll have a ponder whether there might be a better alternative. We have made the default configuration immutable recently, so maybe not as bad an issue as previously. If you passed in a config and retained a reference to it, you could change the config in any case.

**Comment by je-ik** [comment]
@paulk-asert If I understand the problem correctly, you don't want to leak CompilerConfiguration from GroovyClassLoader, right? Does the last commit solve that?

**Comment by je-ik** [comment]
@paulk-asert @danielsun1106 can we get this into upcoming 3.0.0-beta-3 release, please?

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Comment by je-ik** [comment]
@danielsun1106 thanks! :-)

**Pull request merged**
