### PR TITLE
GROOVY-7636: Fall back to BigDecimalMath for custom Numbers

### PR DESCRIPTION
**Pull request by tkruse**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request. :)

Sadly it does not compile on the ci-server:

http://ci.groovy-lang.org/viewLog.html?buildId=28269&tab=buildResultsDiv&buildTypeId=Groovy_Jdk6Build&guest=1

**Comment by tkruse** [comment]
fixed... touch wood

**Comment by PascalSchumacher** [comment]
No luck :( : http://ci.groovy-lang.org/viewLog.html?buildId=28327&tab=buildResultsDiv&buildTypeId=Groovy_Jdk6Build&guest=1

**Comment by tkruse** [comment]
looks good now

**Comment by msgilligan** [comment]
@glaforge: What will it take to get this in the next release of Groovy?

**Comment by paulk-asert** [comment]
PR merged, thanks!

**Pull request closed without merging**
