### PR TITLE
GROOVY-9059: use redirect in generics spec if redirect is placeholder

### PR DESCRIPTION
**Pull request by eric-milles**
When resolving a type parameter like "X extends Y", instead of adding "X: X -> Object" to the generics spec, add "X: Y -> Object" to the spec and continue checking the spec if a returned type is a placeholder.

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

**Comment by danielsun1106** [comment]
I am really happy to know you could set aside time to fix generics bugs, which are usually hard and may cost hours to fix and iron out wrinkles. Thanks a lot for your contribution!

BTW, do you notice GROOVY-8409(https://issues.apache.org/jira/browse/GROOVY-8409)? It is hard to fix but quite important for type system too. If you could set aside time to investigate it, that would be great :-)

**Comment by eric-milles** [comment]
I can take a look at 8409.  I will need to send in my unit test refactors; they allowed me to compile far enough in IDE to run debug on unit tests.

________________________________

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Pull request merged**
