### PR TITLE
upgraded ASM to 7.1, added Java 13 to CompilerConfiguration

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by paulk-asert** [comment]
+1

**Comment by keeganwitt** [comment]
Any objection to including this on the 2.5 line?

**Comment by paulk-asert** [comment]
Works for me. Let's wait a day or two and see if anyone else has an opinion.

**Comment by paulk-asert** [comment]
Merged into the 2_5_X branch.
See also: https://issues.apache.org/jira/browse/GROOVY-9020

**Pull request closed without merging**
