### PR TITLE
GROOVY-9635: resolve "V" in T=V; "T" may have been reused as type param

### PR DESCRIPTION
**Pull request by eric-milles**
https://issues.apache.org/jira/browse/GROOVY-9635

### CODE REVIEW

**Comment by paulk-asert** [comment]
The following script fails with a `VerifyError` with this PR merged:
```
import java.util.function.Function
@groovy.transform.CompileStatic
class C<R extends Number> {
    def <V> V m(Function<C, V> f) { // R from C is confused with R->V from Function
        V result = f.apply(this)
        return result
    }
}

@groovy.transform.CompileStatic
def method() {
    def ret = new C().m(new Function<C, String>() {
        @Override
        String apply(C that) {
            return 'foo'
        }
    })
    assert ret == 'foo'
}

method()
```

**Comment by eric-milles** [comment]
Is it because a Number type is never supplied for C?

**Comment by eric-milles** [comment]
So the issue is somewhere in the anon. inner class created for `Function<C, String>`.  When I replace it with closure coercion, I don't get the error.  I don't know that this problem didn't exist before these changes.
```groovy
@groovy.transform.CompileStatic
Function<C, String> func() {
  /*
  new Function<C, String>() {
    @Override
    String apply(C that) {
      return 'foo'
    }
  }
  */
  { that -> 'foo' } as Function<C, String>
}
```

Here is the error I get.  Any idea what "invariant" refers to?  Is this coming from the contracts module integration?
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    ConsoleScript14$1.invariant_ConsoleScript14$1()V @55: invokevirtual
  Reason:
    Type 'ConsoleScript14' (current frame, stack[0]) is not assignable to 'java/lang/Boolean'
```

Any idea why I get this error when creating a full distribution and running within Groovy Console and not when running via GroovyShell through the unit tests?

**Comment by eric-milles** [comment]
This is the java decompilation that Groovy Console is producing for the anonymous inner class:
```
@groovy.contracts.Contracted
public class script1599241127913$1 extends java.lang.Object implements java.util.function.Function<C, String>, groovy.lang.GroovyObject { 

    final script1599241127913 this$0 
    static final boolean $GCONTRACTS_ENABLED 
    private static org.codehaus.groovy.reflection.ClassInfo $staticClassInfo 
    public static transient boolean __$stMC 
    private transient groovy.lang.MetaClass metaClass 

    script1599241127913$1(script1599241127913 p0) {
        this$0 = p0 
        super()
        metaClass = /*BytecodeExpression*/
    }

    @java.lang.Override
    public java.lang.String apply(C that) {
        return 'foo'
    }

    ...

    protected void invariant_script1599241127913$1() {
        if ( $GCONTRACTS_ENABLED ) {
            try {
                if (org.apache.groovy.contracts.generation.ContractExecutionTracker.track('script1599241127913$1', 'void invariant_script1599241127913$1()', 'invariant', false)) {
                    java.lang.Boolean $_gc_result = false
                    org.apache.groovy.contracts.ViolationTracker.init()
                    $_gc_result = true
                    if (!($_gc_result.booleanValue())) {
                        if (org.apache.groovy.contracts.ViolationTracker.violationsOccurred()) {
                            try {
                                org.apache.groovy.contracts.ViolationTracker.rethrowFirst()
                            } 
                            finally { 
                                org.apache.groovy.contracts.ViolationTracker.deinit()
                            } 
                        }
                    }
                }
            } 
            finally { 
                org.apache.groovy.contracts.generation.ContractExecutionTracker.clear('script1599241127913$1', 'void invariant_script1599241127913$1()', 'invariant', false)
            } 
        }
    }

    ...

    static { 
        $GCONTRACTS_ENABLED = org.apache.groovy.contracts.generation.Configurator.checkAssertionsEnabled('script1599241127913$1')
    }

    @groovy.transform.Generated
    public volatile java.lang.Object apply(java.lang.Object param0) {
    }

}
```

**Comment by paulk-asert** [comment]
Found it. There was a misnamed metadata key in groovy-contracts. I am surprised more things didn't break, but fixed now in any case.

**Comment by paulk-asert** [comment]
Merged, thanks!

**Pull request closed without merging**
