### PR TITLE
GROOVY-7705: Add bridge methods for setting private fields of outer c…

### PR DESCRIPTION
**Pull request by shils**
…lass from inner class or closure

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
No negative feedback, plenty of tests, build passes. I guess this is good to merge?

**Comment by shils** [comment]
@melix @blackdrag could you take a look at this if you haven't already? @PascalSchumacher I also want to add a test for the case of multiple bridge methods before merging.

**Comment by blackdrag** [comment]
I would have liked Cedric to comment here, but if he has no time atm, then I suggest to just merge it. He can still complain later ;) The commit itself looks good to me

**Comment by shils** [comment]
Merged, thanks for reviewing.

**Pull request closed without merging**
