### PR TITLE
Joint build Groovy & Grails

### PR DESCRIPTION
**Pull request by erichelgeson**
I believe this will need to be cherry-picked to GROOVY_2_5_X so it runs on that branch as well. 

Master as noted in the comments will not work until Grails has a branch compatible with Groovy 4.

The job currently fails as there is a reported regression in Groovy 3.0.5.

### CODE REVIEW

**Comment by paulk-asert** [comment]
Merged, thanks!

**Comment by danielsun1106** [comment]
@paulk-asert 
As @erichelgeson said, the job currently fails as there is a reported regression in Groovy 3.0.5:

https://github.com/apache/groovy/runs/828911951
```

> Task :grails-web-databinding:compileGroovy FAILED

FAILURE: Build failed with an exception.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.

See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
* What went wrong:
117 actionable tasks: 78 executed, 39 up-to-date
Execution failed for task ':grails-web-databinding:compileGroovy'.
> BUG! exception in phase 'class generation' in source unit '/home/runner/work/groovy/grails-core/grails-web-databinding/src/main/groovy/grails/web/databinding/GrailsWebDataBinder.groovy' At line 541 column 33
  On receiver: obj with message: getAt and arguments: propName
  This method should not have been called. Please try to create a simple example reproducing
  this error and file a bug report at https://issues.apache.org/jira/browse/GROOVY

```

**Comment by paulk-asert** [comment]
Actually, that is a second regression, but yes, we need to fix that one too.

**Comment by danielsun1106** [comment]
@paulk-asert Gotcha. Also, it's better to check out released tags instead of branches because branches will be updated from time to time and may be affected by some buggy commit... thus it's hard for groovy developers to address issues.

**Comment by erichelgeson** [comment]
@danielsun1106 we want to checkout branches and not releases as we want to catch a bug before it's released! Eg: if a commit is made and pushed to 3_0_X that breaks grails, it's better to know right away rather than right before (or after) a release.

**Comment by paulk-asert** [comment]
I think branches on the Groovy side is fine, I am not 100% sure but I think Daniel was suggesting tags on the Grails side. There are pros and cons of each approach. If it is branches on both sides, that is two moving targets and always hard to know on which side caused the error.

**Comment by erichelgeson** [comment]
@paulk-asert Ahh I see now. Both projects now have joint jobs now - so if we want to adjust in the future we can.

**Comment by paulk-asert** [comment]
For 2_5_X, you need to change the return type of the `exit` methods for the classes that extend `groovy.ui.Console`. It now has a bridge method for any pre-compiled usages but re-compiling against that code needs to change the type. This is already done in master, so perhaps just copying that change but without swapping to the new Groovy 3 class (package rename due to split packaging).

**Comment by erichelgeson** [comment]
@paulk-asert I get an error either way:

Change it to groovy 2.5.13 (leaving void) I get:
```
> Task :grails-console:compileGroovy FAILED
startup failed:
/Users/erichelgeson/source/grails-core/grails-console/src/main/groovy/grails/ui/console/support/GroovyConsoleApplicationContext.groovy: 47: The return type of boolean exit(java.util.EventObject) in grails.ui.console.support.GroovyConsoleApplicationContext$1 is incompatible with void in groovy.ui.Console
. At [47:13]  @ line 47, column 13.
               @Override
```

Change it to boolean, I get:
```
/Users/erichelgeson/source/grails-core/grails-console/src/main/groovy/grails/ui/console/support/GroovyConsoleApplicationContext.groovy: 47: The return type of void exit(java.util.EventObject) in grails.ui.console.support.GroovyConsoleApplicationContext$1 is incompatible with boolean in groovy.ui.Console
. At [47:13]  @ line 47, column 13.
               @Override
```

**Comment by paulk-asert** [comment]
Are your error messages around the wrong way? The void variant is meant to be a synthetic bridge method and shouldn't be checked against. Does removing `@Override` help?

**Comment by erichelgeson** [comment]
Yes, copy/pasted in reverse order, but issue stays the same :) Removing override does not change the issue.

**Comment by paulk-asert** [comment]
We are checking for synthetic/bridge only on the overriding method (`overridingMethod`) not parent method (`oldMethod`):
https://github.com/apache/groovy/blob/GROOVY_2_5_X/src/main/java/org/codehaus/groovy/classgen/Verifier.java#L1347
I'll have to trace through whether the bridge method is getting passed through as `oldMethod`.

**Comment by paulk-asert** [comment]
Can you try the latest SNAPSHOT after changing to boolean?

**Pull request closed without merging**
