### PR TITLE
Character filter for MarkupBuilder

### PR DESCRIPTION
**Pull request by tosts**
Could this work?

### CODE REVIEW

**Comment by tosts** [comment]
Also: Not sure what I should do about a timeout in the sonar checks. Does that have something to do with me?

**Comment by paulk-asert** [comment]
Parts of this look good but we can possibly re-work to increase the likelihood of being able to extend to `StreamingMarkupBuilder`. I'll take a look.

**Comment by tosts** [comment]
Like so?

**Comment by paulk-asert** [comment]
It's been a while since I delved into XML encoding rules. We take a slightly different approach for surrogates (potentially writing them as hex strings) in StreamingMarkupWriter:
https://github.com/apache/groovy/blob/master/subprojects/groovy-xml/src/main/java/groovy/xml/streamingmarkupsupport/StreamingMarkupWriter.java#L141-L170
Do you see anything wrong with that approach?

**Comment by paulk-asert** [comment]
Merged with a few changes. Thanks!

**Comment by tosts** [comment]
Great! \o/

@Surrogates: No, as a default for writing HTML that's probably even desirable.
They just live in the intenional limbo of no MUST in XML, but not discouraged either.

Ha, and you caught me. I copy-pasted a bit too much on my explanatory comments.
Let met fix that real quick...

**Comment by tosts** [comment]
Over here: https://github.com/apache/groovy/pull/1372
Sorry for the extra round-trip.

**Pull request closed without merging**
