### PR TITLE
GROOVY-9352: Static compilation fails with NoClassDefFoundError

### PR DESCRIPTION
**Pull request by danielsun1106**

### CODE REVIEW

**Comment by danielsun1106** [comment]
@melix Thanks for your reviewing. I'll port the fix to 2_5_X later. It's very late for me to sleep... (5:09 a.m.)

**Comment by eric-milles** [comment]
This is a lot of change with very little review.  Already merged into 3.0...  The issue is hardly 7 hours old.

Why isn't a change of this scope on a branch that has others able to pull down and try out to judge benefit vs cost.

**Comment by PascalSchumacher** [comment]
`LazyConstructorNode` etc. override `hashCode`. Shouldn't `equals` also be overriden? Or am I missing something?

Thanks,
Pascal

**Comment by danielsun1106** [comment]
@PascalSchumacher I will refine it later. Thanks for your reviewing :-)

**Pull request merged**
