### PR TITLE
GROOVY-9008: Support native method reference and constructor reference (basic cases)

### PR DESCRIPTION
**Pull request by danielsun1106**

### CODE REVIEW

**Comment by danielsun1106** [comment]
It's really weird... Tests pass on my local machine( https://gradle.com/s/iet2cjgpvrex4 ) , but fail on travis CI ( https://gradle.com/s/pvizsvfhnymgs ).
P.S. I use Corretto openjdk locally.
```
openjdk version "11.0.2" 2019-01-15 LTS
OpenJDK Runtime Environment Corretto-11.0.2.9.1 (build 11.0.2+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.2.9.1 (build 11.0.2+9-LTS, mixed mode)
```

**Comment by danielsun1106** [comment]
I use oracle jdk 8 locally now, all tests pass too( https://gradle.com/s/3pwi5afid6iww )
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by danielsun1106** [comment]
@paulk-asert Could you please check out the PR and run tests on your machine?

**Comment by danielsun1106** [comment]
@paulk-asert I can reproduce the issue by myself. Thanks all the same :-)

**Comment by paulk-asert** [comment]
+1, I have squashed a few of the commits but mostly left them as is. I'll merge now. I have added one bytecode test but am still working on doco. I'll do that and any tweaks, if needed, post merge.

**Comment by danielsun1106** [comment]
Thanks, Paul 😃

**Pull request closed without merging**
