### PR TITLE
Fix some bad code

### PR DESCRIPTION
**Pull request by blindpirate**
I did an analysis in IDEA and fixed some bad code.

### CODE REVIEW

**Comment by paulk-asert** [comment]
Merged, thanks. For some reason the auto close didn't work. Please feel free to close.

**Comment by pzygielo** [comment]
> For some reason the auto close didn't work.

I see some commits to 25X and 30X branches but not to master as requested by Author. As no change with auto-closing comment was commited to default branch of repository GH didn't act on them I guess.

**Comment by paulk-asert** [comment]
Looks like the glitch we had a few days ago is still affecting things. Locally I have the commit to master but agree it isn't showing up in the GUI commit history. I'll try re adding manually.

**Comment by pzygielo** [comment]
@paulk-asert Hi Paul
As master branches on gitbox and github diverged, with GH having it at 7f3675ea29, one can do following (not limited to):
1. with GH admin priviliges for this repo - force push gitbox master to github, as 7f3675ea29 is in gitbox as c652220bb0
or
1. merge GH master as suggested by `You may want to first integrate the remote changes`. If you pull and everything is up-to date, you are pulling from gitbox I suppose. So you could do, assuming your master is even with gitbox master:
```
git fetch https://github.com/apache/groovy master:ghmaster
git merge ghmaster
git push
git branch -D ghmaster
```
It will allow master on GH to advance to newly created commit on sync (but it can't be *squashed one*, it has to have links between merged commits). It would look like this: https://github.com/apache/groovy/compare/master...pz-apache:gh_gb_masters?expand=1

**Comment by paulk-asert** [comment]
Yes, gitbox is the real master. GH is the mirror. We don't have admin privileges on GH. I'll see what ASF infra say.

**Pull request closed without merging**
