### PR TITLE
this is a wrong PR ，please delete it.thanks

### PR DESCRIPTION
**Pull request by chilatiaobushanghuo**

### CODE REVIEW

**Comment by danielsun1106** [comment]
Are you kidding?

**Comment by paulk-asert** [comment]
Wrong branch?

**Comment by chilatiaobushanghuo** [comment]
I don't know. I'm a novice. I want to see the PR function. The result is wrong. That's it. If it's inconvenient, please delete it. Thank you.

**Comment by paulk-asert** [comment]
We can't delete it. You should be able to close or delete it. If you are unable, I can close it for you. Just looking at it, it appears that you have based the PR on the GROOVY_1_7_X branch which is very old, so included in your PR is every change we have made since that branch as well as I presume some changes you have made. You are usually best making the PR wrt Groovy's master branch and a newly created branch on your repo.

**Comment by chilatiaobushanghuo** [comment]
OK,thanks so much

**Pull request closed without merging**
