### PR TITLE
Add source dependency on task to fix task cacheability

### PR DESCRIPTION
**Pull request by runningcode**
The deprecation warning that this PR fixes can be seen [in this build scan](https://scans.gradle.com/s/njuvm77j3jark/deprecations?expanded=WyI1OSJd#60)

### CODE REVIEW

**Comment by daniellansun** [comment]
```
> Task :groovy-xml:asciidoctor
Dependency verification has been disabled for configuration detachedConfiguration2
Dependency verification has been disabled for configuration detachedConfiguration3
error: Illegal package name: "/home/runner/work/groovy/groovy/build/generated/sources/antlr4/org/apache/groovy/parser/antlr4/GroovyLexer.tokens"
```

The distribution build is failing because of the above error, so the PR can not be merged for now.

**Comment by runningcode** [comment]
Thanks, do you mean that the build in general is failing? Or that this PR caused this failure?

**Comment by daniellansun** [comment]
The build is still failing:
https://github.com/apache/groovy/actions/runs/3886703609/jobs/6634225416#step:6:569

**Comment by runningcode** [comment]
@daniellansun sorry for the delay. I've pushed up a commit that should fix the failing build.

**Comment by runningcode** [comment]
@daniellansun looks like the build is green!

**Pull request merged**
