### PR TITLE
GROOVY-9637: Improve the performance of GString

### PR DESCRIPTION
**Pull request by paulk-asert**
Co-authored-by: Daniel Sun sunlan@apache.org

### CODE REVIEW

**Comment by paulk-asert** [comment]
@blackdrag this is the other alternative I alluded to in earlier comments. No change to `GString`, `GStringImpl` enhanced slightly with a flag that enables defensive copy in/out for the string and value arrays. We create GStrings in @CompileStatic code with that flag set. Caching is only enabled when that flag is set and values are simple immutables. This piggy-backs on the idea that @CS turns off "dynamic behaviors" even though mutating those arrays is a bit of a stretch of what constitutes dynamic behavior.

**Comment by paulk-asert** [comment]
Daniel's simple benchmark:
```
long b = System.currentTimeMillis()
def gstr = makeGString()
for (int i = 0; i < 10000000; i++) {
	gstr.toString()
}
long e = System.currentTimeMillis()
println "${e - b}ms"

//@groovy.transform.CompileStatic
def makeGString() {
    def now = java.time.LocalDateTime.now()
    "integer: ${1}, double: ${1.2d}, string: ${'x'}, class: ${Map.class}, boolean: ${true}, now: ${now}"
}

```

**Comment by blackdrag** [comment]
My feeling is that stretch is a bit too far.

**Comment by paulk-asert** [comment]
Closing this one but see:
https://github.com/apache/groovy/pull/1329

**Pull request closed without merging**
