### PR TITLE
 GROOVY-9168: emit more specific error for use of uninitialized this

### PR DESCRIPTION
**Pull request by eric-milles**
Improved error message for cases like:
```groovy
class Outer {
  class Inner {}
  Outer(Inner inner) {}
  Outer() { this(new Inner()) } // uninitialized this passed to inner class constructor
}
```
Simplified `StaticVerifier` and handle `this.@foo` and `this.&foo` in addition to `this.foo` and implicit-this `foo()`.  Special constructor call args and parameter defaults have unified handling.

One test case was disabled.  It is not possible to distinguish this case from other error cases.  And you can add `Outer.this.` qualifier to reference the property (next test case in the unit test source).
```groovy
    void _FIXME_testAccessOuterClassMethodFromInnerClassConstructor() {
        assertScript '''
            class Parent {
                String str
                Parent(String s) { str = s }
            }
            class Outer {
                String a

                private class Inner extends Parent {
                   Inner() { super(getA()) } // Is this a reference to instance property or outer property?
                }

                String test() { new Inner().str }
            }
            def o = new Outer(a:'ok')
            assert o.test() == 'ok'
        '''
    }
```

### CODE REVIEW

**Comment by eric-milles** [comment]
There is a redundant check in `Verifier.visitConstructor` (included below).  Is this the better place to do checking for uninitiualized this/super references -- instead of in `StaticVerifier`?  I think `Verifier` runs later and could catch references added by the compiler.

```java
    @Override
    public void visitConstructor(ConstructorNode node) {
        GroovyCodeVisitor checkSuper = new CodeVisitorSupport() {
            boolean firstMethodCall = true;
            String type = null;

            @Override
            public void visitMethodCallExpression(MethodCallExpression call) {
                if (!firstMethodCall) return;
                firstMethodCall = false;
                String name = call.getMethodAsString();
                // the name might be null if the method name is a GString for example
                if (name == null) return;
                if (!name.equals("super") && !name.equals("this")) return;
                type = name;
                call.getArguments().visit(this);
                type = null;
            }

            @Override
            public void visitConstructorCallExpression(ConstructorCallExpression call) {
                if (!call.isSpecialCall()) return;
                type = call.getText();
                call.getArguments().visit(this);
                type = null;
            }

            @Override
            public void visitVariableExpression(VariableExpression expression) {
                if (type == null) return;
                String name = expression.getName();
                if (!name.equals("this") && !name.equals("super")) return;
                throw new RuntimeParserException("cannot reference " + name + " inside of " + type + "(....) before supertype constructor has been called", expression);
            }
        };
        Statement s = node.getCode();
        if (s == null) {
            return;
        } else {
            s.visit(new VerifierCodeVisitor(this));
        }
        s.visit(checkSuper);
    }
```

**Comment by eric-milles** [comment]
Also fixes GROOVY-9189

**Comment by eric-milles** [comment]
This should close out GROOVY-6777, GROOVY-6809, GROOVY-7609, GROOVY-9168, and GROOVY-9189.

**Comment by eric-milles** [comment]
Builds are timing out at 50 min, which is very close to the amount of time they require now.

**Comment by danielsun1106** [comment]
Yep. Maybe we have to remove `testWithIndy` as before.

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Pull request closed without merging**
