### PR TITLE
GROOVY-10871: Bump Gradle version (build dependency)

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by Goooler** [comment]
The issue of Asciidoctor Gradle Plugin had been filed at https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/655.

**Comment by paulk-asert** [comment]
> The issue of Asciidoctor Gradle Plugin had been filed at [asciidoctor/asciidoctor-gradle-plugin#655](https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/655).

Thanks, yes I saw your issue (Thanks!) and already have the link in the Jira issue:
https://issues.apache.org/jira/browse/GROOVY-10871

**Comment by daniellansun** [comment]
Asciidoctor Gradle Plugin is not that active any more...

**Comment by Goooler** [comment]
It outdated, handled by #1899.

**Comment by paulk-asert** [comment]
Indeed, outdated. Closing.

**Pull request closed without merging**
