### PR TITLE
GROOVY-11459: MD5 is already an insecure hash algorithm, replacing it with SHA256 i…

### PR DESCRIPTION
**Pull request by zhangwei911**
https://issues.apache.org/jira/browse/GROOVY-11459

### CODE REVIEW

**Comment by paulk-asert** [comment]
Thanks for your contributions to this topic.  I did a little bit more performance testing and think this topic deserves more discussion. I'll add some results into the corresponding Jira issue and create an email on the dev list shortly. We'll likely make some changes similar to what you are suggesting but some assumptions about algorithm speed weren't as I expected.

**Comment by paulk-asert** [comment]
I'll merge and refactor to be halfway between your suggestion and what I have been doing for testing. Thanks!

**Comment by zhangwei911** [comment]
Thank you very much for doing these tests, and I am very glad that this has been adopted.



---- Replied Message ----
| From | Paul ***@***.***> |
| Date | 09/12/2024 14:05 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [apache/groovy] GROOVY-11459: MD5 is already an insecure hash algorithm, replacing it with SHA256 i… (PR #2112) |

I'll merge and refactor to be halfway between your suggestion and what I have been doing for testing. Thanks!

**Comment by GianniGiglio** [comment]
Hi are there any plans to backport this to groovy 4 release?

**Pull request merged**
