### PR TITLE
GROOVY-7877: Range step method could work with Number not just int (a…

### PR DESCRIPTION
**Pull request by paulk-asert**
…lternative utility method implementation)

### CODE REVIEW

**Comment by paulk-asert** [comment]
Still needs tests - useful as is for discussion purposes. We could have additional variants which took a Range instead of the initial/max params.

**Comment by tkruse** [comment]
Some Javadoc about the purpose of the class and methods would make a review easier.

**Comment by paulk-asert** [comment]
I will add doco at some point. Basically, a moire functional style for the proposed Number variants for step on Range.

**Comment by tkruse** [comment]
Comments: 
* The name "maxAllowedValue" is confusing, since this may be a minimum, something like "limit" might work better
* Not sure how to reuse these methods for a lazy / streaming approach of reading n steps and then aborting prematurely (like StepIterator inner class in ObjectRange)
* 2nd Exception should include feedback information about the values used
* the code path at the bottom half of step when (initialValue == maxAllowedValue and step!=0) looks dodgy and overly complicated, seems to me the final loop will never execute in that case, so code could return early in that case
* inclusive / exclusive limit distinction not yet there
* Not sure if initialValue, limit and step have all to be of same generic type T
* Not sure if while loop with comparison each time might be safely optimized by calculating how many numbers should be passed to closure, saving the time of comparisons (safely means rounding errors safe). 
* Note that adding step n times is also prone to some rounding "influence" compared to adding (i * step) to initialValue in the loop (many rounding errors for each addition vs. 2 rounding errors (1 multiplication and 1 addition).

**Comment by paplorinc** [comment]
Superseded by https://github.com/apache/groovy/pull/360, I think.
If not, let me know how I should include it.

**Comment by paulk-asert** [comment]
Only possibly superseded by #360 but should not be included in #360. The idea was to consider an alternative to #360 that stopped the Range class from getting too complex and didn't suffer from backwards compatibility issues. So, the idea was one or the other. If we go ahead with #360, we would close this one.

**Comment by paulk-asert** [comment]
@tkruse which line are you worried about being "dodgy"?
The "ascending = ascendingStep" line?
That just covers the case when a single number will be selected and makes sure we don't head off in an infinite loop in the wrong direction.

**Comment by tkruse** [comment]
yes, that line. Unless I am mistaken, the while loop cannot be entered anyway in that case, because neither of the two conditions greaterThan and lessThan can be true if both values are same.

**Comment by paulk-asert** [comment]
I am going to close this PR. I have an alternative spike which I'll turn into a PR once finished which takes a slightly different approach.

**Pull request closed without merging**
