### PR TITLE
Backport Gradle 8 updates for Groovy 4 branch

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by Goooler** [comment]
May missing some changes from you, please let me know, I'll pick them up.

**Review by daniellansun — APPROVED** [review]

**Comment by paulk-asert** [comment]
Plan to look at this tomorrow.

**Review by paulk-asert — APPROVED** [review]
There is one or two minor changes I can see but I'll tweak those after the fact.

**Comment by Goooler** [comment]
Thanks!

**Pull request merged**
