### PR TITLE
throw NoSuchElementException instead of returning null

### PR DESCRIPTION
**Pull request by jt1796**
Looking for an easy place to get started.

### CODE REVIEW

**Comment by jwagenleitner** [comment]
Thanks for the PR.  Would you mind creating a JIRA ticket for this change (https://issues.apache.org/jira/browse/GROOVY)?  It helps to have a issue filed since they help to build a changelog for releases.  Also, if you're up for it, the same problem exists in `ObjectRange` if you want to make the same fix there.

**Comment by jwagenleitner** [comment]
I created [GROOVY-7960](https://issues.apache.org/jira/browse/GROOVY-7960) for this and will merge this PR soon unless there are objections.

**Comment by jwagenleitner** [comment]
Ok.  I had opened GROOVY-7961 for ObjectRange when I opened the one for IntRange, so 7962 is a duplicate.

**Comment by blackdrag** [comment]
I think we can merge that

**Comment by paulk-asert** [comment]
+1 (I changed the issue to have a breaking label - this is slightly pedantic as it is an undesirable edge case that will break but it should make it easier to find if anyone is relying on that edge case - see my comments on the issue for further details)

**Comment by jt1796** [comment]
All,
The matching PR is here:
https://github.com/apache/groovy/pull/440

**Comment by jwagenleitner** [comment]
PR merged, thanks!

**Pull request closed without merging**
