### PR TITLE
GROOVY-9456: Bump Gradle Spotbugs plugin to 4.0.0

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by danielsun1106** [comment]
Merged. Thanks.

**Comment by paulk-asert** [comment]
Unfortunately, latest spotbugs plugin is still broken for us. All reports with errors are truncated so as not to show the interesting details.

**Comment by danielsun1106** [comment]
Sad to know...

P.S. I am trying to create a project on the SonarCloud:
https://issues.apache.org/jira/browse/INFRA-19971

Here is the link to show all current Apache projects on the SonarCloud
https://sonarcloud.io/organizations/apache/projects

**Comment by danielsun1106** [comment]
I'm trying to downgrade its version for now...

**Pull request closed without merging**
