### PR TITLE
GROOVY-7604: traits docs diamond problem explanation

### PR DESCRIPTION
**Pull request by andresteingress**
Fixes a (very) tiny text issue raised in GROOVY-7604.

### CODE REVIEW

**Comment by blackdrag** [comment]
can you explain why you don´t want to mention the diamond problem?

**Comment by andresteingress** [comment]
The diamond problem is actually mentioned in one of the following sections. 7604 was just about that the ticket author said that the sub-sentence this PR removes would hint the reader that the following example would be show how to solve the diamon problem, which in fact is not the case.

It's just a tiny correction, I also wont be mad if this ticket is simply ignored and closed.

**Comment by blackdrag** [comment]
+1 for merging then

**Comment by PascalSchumacher** [comment]
Thanks!

**Pull request closed without merging**
