### PR TITLE
GROOVY-9081: CLONE - Fix warning "An illegal reflective access operat…

### PR DESCRIPTION
**Pull request by danielsun1106**
…ion has occurred"

### CODE REVIEW

**Comment by danielsun1106** [comment]
| BRANCH | WARNING COUNT | REPORT LINK |
| ------ | ------ | ------ |
| master | 12 | https://api.travis-ci.org/v3/job/527686477/log.txt |
| PR | 10 | https://api.travis-ci.org/v3/job/527697226/log.txt |

(Search `WARNING: An illegal reflective access` in the build report and count the warnings)

**Comment by danielsun1106** [comment]
@paulk-asert 
The PR will take much time to complete, so feel free to merge some of its commits into master if you think OK before releasing 3.0.0 beta-1

**Comment by danielsun1106** [comment]
| BRANCH | WARNING COUNT | BUILD REPORT LINK |
| ------ | ------ | ------ |
| master | 12 | https://api.travis-ci.org/v3/job/527686477/log.txt |
| PR | 9 | https://api.travis-ci.org/v3/job/527736304/log.txt |

(Search `WARNING: An illegal reflective access` in the build report and count the warnings)

**Comment by danielsun1106** [comment]
After `debug` mode enabled, more warnings appear. Luckily, they can be classified into existing cases:

_( https://api.travis-ci.org/v3/job/527830078/log.txt )_
```
	Line 1229: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to method java.lang.Object.clone()
	Line 1262: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to method java.lang.ClassLoader.loadClass(java.lang.String,boolean)
	Line 1301: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.SecurityTest (file:/home/travis/build/danielsun1106/groovy/target/classes/groovy/test/) to method java.lang.ClassLoader.defineClass(java.lang.String,java.nio.ByteBuffer,java.security.ProtectionDomain)
	Line 1334: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to method java.lang.ClassLoader.defineClass(java.lang.String,java.nio.ByteBuffer,java.security.ProtectionDomain)
	Line 1388: WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
	Line 1435: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to method java.lang.String.isLatin1()
	Line 1495: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/libs/groovy-raw-3.0.0-SNAPSHOT.jar) to method java.io.File.isInvalid()
	Line 1528: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/libs/groovy-raw-3.0.0-SNAPSHOT.jar) to method java.io.File.getPrefixLength()
	Line 1568: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedMethod (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to field java.lang.reflect.Field.modifiers
	Line 1601: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedMethod (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to field java.lang.reflect.Field.modifiers
	Line 1634: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedMethod (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to field java.lang.reflect.Field.modifiers
	Line 1667: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedMethod (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to field java.lang.reflect.Field.modifiers
	Line 1754: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to method java.math.BigInteger.multiply(long)
	Line 1832: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedMethod (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to field java.lang.reflect.Field.modifiers
	Line 1865: WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/home/travis/build/danielsun1106/groovy/target/classes/java/main/) to field java.util.Observable.changed
```

**Comment by paulk-asert** [comment]
+1

**Pull request closed without merging**
