### PR TITLE
Modified `MapWithDefault` to not store the default value

### PR DESCRIPTION
**Pull request by paplorinc**
Please see https://github.com/careercup/CtCI-6th-Edition-Groovy/blob/d116d65469bdf17d1e215e89f3e76ac3a97660a9/src/main/groovy/Ch04_TreesAndGraphs/_04_12_PathsWithSum.groovy#L21 for valid usecases

### CODE REVIEW

**Comment by jwagenleitner** [comment]
If I put entries in the map, even if I set them to the default value, I would expect to be able to iterate over them using methods such as `keySet()/entrySet()`.  However that would no longer work with this change in place.

**Comment by paplorinc** [comment]
Hello @jwagenleitner :)

I agree, that's what I would expect in case of a normal map also.
But I would also expect `containsKey` to return `false`, if I haven't inserted anything, but that's not the current behavior.
```Groovy
def x = [:].withDefault {0}
println x.containsKey(1) // false
println x[1]                      // 0
println x.containsKey(1) // true
```
Therefore I think this new behavior is consistent with the class.

If you don't agree, I have a few alternative ideas, like:
* removeIfDefault(Object) // removes current key, if value is equal to default
* consolidate() // removes all default values
* constructor parameter `boolean storeDefaultValues = false`

**Comment by jwagenleitner** [comment]
In your example `println x[1]` does insert an entry in the map.  If you used `keySet()/entrySet()` you'd be able to iterate.  I think it's expected that by calling `get` you are ensuring that entry will be added if it does not exist already.

Of the alternatives, I think the constructor parameter might work the best so then you could construct the map like this:

`[:].withDefault(false) { 7 }`

I'd recommend opening a JIRA for this feature, hopefully that would generate some more discussion.

**Comment by paplorinc** [comment]
ok, sure, will do.

I know the `getAt` inserts it, that's why I gave it as an example - I find it confusing that a get will insert.

**Comment by jwagenleitner** [comment]
I would agree that if there is a new option to not store the default value, then `get` should be changed to just return the value and not add to the delegate.

**Comment by paplorinc** [comment]
... but that would be confusing also, because e.g.
```Groovy
def x = [:].withDefault { [] }
x[1] << 0
println x // [1:[0]]
```
wouldn't work anymore

**Comment by jwagenleitner** [comment]
You're right, good point.  So even with the proposed change it not correct to say that the default wont be stored since it will for `get` just not `put`.

**Comment by paplorinc** [comment]
Yeah, that's why I pointed it out.
Where should I open an issue for this?

**Comment by PascalSchumacher** [comment]
@paplorinc You can open issue for groovy at https://issues.apache.org/jira/browse/GROOVY

**Comment by paplorinc** [comment]
Opened an issue for this PR: https://issues.apache.org/jira/browse/GROOVY-7802

**Comment by paulk-asert** [comment]
Closing this as there is now a revised PR over on the Apache Groovy site:
https://github.com/apache/groovy/pull/1692

**Pull request closed without merging**
