### PR TITLE
GROOVY-9394: Groovy could provide some minimal methods to assist with…

### PR DESCRIPTION
**Pull request by paulk-asert**
… migrating between Groovy versions

### CODE REVIEW

**Comment by danielsun1106** [comment]
+1

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Comment by eric-milles** [comment]
There are several instances of this type of comparison in CompilerConfiguration's isPostJDK methods.

**Comment by paulk-asert** [comment]
@danielsun1106 Thanks for merging.
@eric-milles Thanks for noting that, I'll take a look.

**Pull request merged**
