### PR TITLE
GROOVY-9202: Bump picocli to 4.0.1

### PR DESCRIPTION
**Pull request by danielsun1106**

### CODE REVIEW

**Comment by remkop** [comment]
I just saw this, Daniel, thanks!
I will run the tests and take care of this one if that is okay with you.

**Comment by danielsun1106** [comment]
@remkop I find 4.0.1 is not compatible with 3.9.6. Any help is appreciated :-)

**Comment by remkop** [comment]
I started to work on this now. When you say "not compatible" do you mean binary incompatible or failing tests (because the error message changed, for example)?

**Comment by danielsun1106** [comment]
I mean the failing tests.

**Comment by remkop** [comment]
Having some environment issues... 
I was able to run the CliBuilder tests but not the full test suite.
Is there a link where I can check that the continuous build succeeded?

Also, still need to cherry-pick this to the 2.5.x branch.

**Comment by danielsun1106** [comment]
@remkop 

Here is the link to travis CI: https://travis-ci.org/apache/groovy/builds/562357468?utm_source=github_status&utm_medium=notification

P.S. TeamCity CI has been down for a long time...

**Pull request closed without merging**
