### PR TITLE
Remove antlr2 related code in `LexerFrame`

### PR DESCRIPTION
**Pull request by danielsun1106**

### CODE REVIEW

**Comment by paulk-asert** [comment]
Maybe we should set  up a parallel package, e.g. org.apache.groovy.antlr.LexerFrame
We could leave the codehaus one generic supporting other lexer/tokentype combinations but deprecate it.
Then perhaps for the new apache version hard code the tokenTypesClass class as well as the lexerClass (not just the lexerClass as in this PR)?

**Comment by danielsun1106** [comment]
@paulk-asert The PR has been adjusted. Pls review it again.

**Comment by paulk-asert** [comment]
What about leaving codehaus version as is in GROOVY_3_0_X but just mark as deprecated then have new apache version in 3 and 4? This gives anyone using it the whole of 3 to convert over?

**Comment by paulk-asert** [comment]
Merged! Thanks!

**Pull request closed without merging**
