### PR TITLE
GROOVY-9272: Support switch expression

### PR DESCRIPTION
**Pull request by danielsun1106**
https://issues.apache.org/jira/browse/GROOVY-9272

### CODE REVIEW

**Comment by eric-milles** [comment]
Looks good so far.  When using `callX` to create a method call to the closure, you should `setImplicitThis(false)` on the returned `MethodCallExpression`.

Any idea of level of compatibility with the Java switch expression variants?  Does this cover them all or are there known limitations?  Is there any measure of performance impact versus current parser?

**Comment by danielsun1106** [comment]
> Looks good so far. When using callX to create a method call to the closure, you should setImplicitThis(false) on the returned MethodCallExpression.

Tweaked. Thanks!

> Any idea of level of compatibility with the Java switch expression variants?

Groovy should be able to support all variants of switch expression of the latest JEP.

> Is there any measure of performance impact versus current parser?

No, it should be a bit impact because the build time does change obviously.

**Comment by eric-milles** [comment]
Is there any more coming for this change?  Or is the plan to wait until after 4.0b1?  I'd like to see it as part of the beta myself.

**Comment by danielsun1106** [comment]
> Is there any more coming for this change? Or is the plan to wait until after 4.0b1? I'd like to see it as part of the beta myself.

No more changes for this PR, but I am waiting @paulk-asert to review it ;-)

**Comment by paulk-asert** [comment]
Yes, I've been busy on other things the last few weeks. I'm looking at it this week. I won't proceed with beta-1 until finished.

**Pull request closed without merging**
