### PR TITLE
GROOVY-7044: Fixed deep cloning of nodes generated by NodeBuilder

### PR DESCRIPTION
**Pull request by daspilker**
Use default behavior when creating Nodes without value.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@paulk-asert I guess this is good to merge? What do you think?

**Comment by PascalSchumacher** [comment]
@paulk-asert Any opinion on this?

**Comment by paulk-asert** [comment]
+1

**Comment by shils** [comment]
Merged, thanks!

**Pull request closed without merging**
