### PR TITLE
GROOVY-9480: New v9 ClassFinder throws NoSuchFileException/Unsupporte…

### PR DESCRIPTION
**Pull request by danielsun1106**
…dOperationException and writes it to stderr

### CODE REVIEW

**Comment by paulk-asert** [comment]
+1

**Comment by eric-milles** [comment]
Not sure I agree with this change.  I filed the bug because the exception was coming for 1) trying to close a file system handle that does not support it and 2) tyring to find "groovy" in the root of a project that does not have such a directory.

**Comment by paulk-asert** [comment]
@eric-milles Do you have a reproducer for those cases?

**Comment by eric-milles** [comment]
In my environment, `org.codehaus.groovy.vmplugin.v9.Java9#getDefaultImportClasses` is called and its request `DefaultGroovyMethods.getLocation(gcl.loadClass("groovy.grape.GrapeIvy")).toURI()` returns:
```
file:/C:/Users/.../org.codehaus.groovy30/
```

`getDefaultImportClasses` makes the assumption that the URI returned will then have a "groovy" package under it.  And that's just not how the class loader that provides a GrapeIvy class works in my environment.

This is a different flavor of the existing note "in production environment, groovy-core classes, e.g. `GroovySystem`(java class) and `GrapeIvy`(groovy class) are all packaged in the groovy-core jar file, but in Groovy development environment, groovy-core classes are distributed in different directories".

Also, you cannot assume that in production they are sourced from the same archive since you could use the patch modules feature of JPMS or OSGi to add classes from another archive.

**Pull request merged**
