### PR TITLE
upgraded gradlew from 3.0-20160715000024+0000 to 3.0

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by paulk-asert** [comment]
+1

**Comment by keeganwitt** [comment]
Any suggestions for debugging Travis failure? It works locally.

**Comment by paulk-asert** [comment]
Works locally for me too. I'd punt on a sporadic error on the CI server and commit. Hopefully not famous last words! :-)

**Comment by keeganwitt** [comment]
Lol.  I was looking for a button to re-kick Travis, but couldn't find it anywhere.

**Pull request closed without merging**
