### PR TITLE
null-safe and empty-safe number parsing of xml

### PR DESCRIPTION
**Pull request by mortensoby**
The following results in af NumberFormatException:
xml.'**'.find{it.name()` == 'someBigDecimal'}.toBigDecimal()
if the element content is empty which means the following construct is necessary:

```
xml.'**'.find{it.name() == 'someEmptyBigDecimal' && it.text()}?.toBigDecimal()
```

This pull request ensures that null is returned if the element is empty for the following methods:
```
toBigInteger()
toBigDecimal()
toDouble()
toBigLong()
toBigFloat()
```

### CODE REVIEW

**Comment by blackdrag** [comment]
btw, would it be possible to rebase the branch on master?

**Comment by mortensoby** [comment]
Done. The new pull request is here: https://github.com/apache/groovy/pull/494

**Comment by mortensoby** [comment]
There is a similar pull request for Node here: https://github.com/apache/groovy/pull/494

**Comment by paulk-asert** [comment]
I guess it is safe to close this pull request.

**Comment by mortensoby** [comment]
Yes it is.

**Comment by paulk-asert** [comment]
As the creator of the PR it's easiest for you to close. But if you can't, let us know and we can force it closed as a side-effect of a commit containing a particular message - it's a standard Apache process.

**Pull request closed without merging**
