### PR TITLE
GROOVY-4018: Make the Groovy truth value of NaN be false

### PR DESCRIPTION
**Pull request by jwagenleitner**
Just thought I'd take a stab at implementing this, maybe there are performance concerns with this.  It may be more efficient to use `FLOAD`/`DLOAD` before the `isNaN` call instead of the `DUP2` up front, but in the context of those methods I wasn't sure how to access the index of the variable on the stack.

### CODE REVIEW

**Comment by paulk-asert** [comment]
+1, looks okay to me but I'm not super familiar with how performance might be affected at this level

**Comment by jwagenleitner** [comment]
Thanks for looking it over, I appreciate it.

I'll let it sit for a while and see if I can get some time to do a quick benchmark.  Not sure how often `floats/doubles` are used in tight loops and compared using the Groovy Truth, but probably wouldn't hurt to make sure it's not too costly of an extra check for `NaN`.

**Comment by jwagenleitner** [comment]
Updated the PR to consolidate the primitive-to-boolean conversion for both prim opts and static compilation and changed since tags to `3.0.0`.

**Comment by paulk-asert** [comment]
LGTM. How about we change the since version to 2.6.0 and merge into master and GROOVY_2_6_X?

**Comment by jwagenleitner** [comment]
Thanks Paul, I updated the since tags and merged into the branches suggested.

**Pull request closed without merging**
