### PR TITLE
More examples for AST transformation classes in Javadoc

### PR DESCRIPTION
**Pull request by mrhaki**
* Give readers of the Javadoc documentation more example code
* Examples based on MrHaki's Groovy Goodness blog posts

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks!

I guess the examples are executable? If that is the case, could you please use `<pre class="groovyTestCase">` so that they are executed during the build (like Paul did in: https://github.com/apache/groovy/commit/aa38aca0b93036453df7859de3f2a9992ab40358)?

**Comment by mrhaki** [comment]
Hi, I didn't know that appending the CSS class groovyTestCase would trigger a real test. I will add it where it is appropriate.

**Comment by PascalSchumacher** [comment]
Thanks!

It's a well hidden feature ;) :(. 

With `<pre class="groovyTestCase">` you mark the code so that https://github.com/apache/groovy/blob/master/subprojects/groovy-test/src/main/groovy/groovy/util/JavadocAssertionTestBuilder.groovy will find it and build a test-suite. The suite is then run by https://github.com/apache/groovy/blob/master/src/test/MainJavadocAssertionTest.groovy. 

JavadocAssertionTestBuilder is distributed with Groovy, so everybody could use it, but I do not know if it is documented anywhere.

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Pull request closed without merging**
