### PR TITLE
GROOVY-7304: handle private field access from closure for ++x and x++

### PR DESCRIPTION
**Pull request by eric-milles**
https://issues.apache.org/jira/browse/GROOVY-7304

### CODE REVIEW

**Comment by eric-milles** [comment]
To merge into Groovy 2.5, you would also need: https://github.com/apache/groovy/commit/8c0c5b018805fcab7217f5cdc784fc88354cfb15, https://github.com/apache/groovy/commit/543c97b6e6bbb67cd6c9c71cac1ca37ac8bd39f4, and https://github.com/apache/groovy/commit/77a11e89b70b4e785fab36b9c3e93c11913288a2

**Comment by paulk-asert** [comment]
This looks close to me. When I have @CS just on the method like in Jochen's example it still fails, but @CS on the class and it works.

**Comment by eric-milles** [comment]
I'll have a look

**Comment by paulk-asert** [comment]
Yes, it is not uncommon. I'll just have to refresh my memory. I'll take a look in parallel if I get time and if I spot something obvious I'll report back here. If we find an obvious fix we can add it here (since that was the original case in the issue) but otherwise we can just clone the issue and fix separately.

**Comment by eric-milles** [comment]
I think I found the culprit.  I will amend the pull request if testing bears out.

**Comment by eric-milles** [comment]
There still seems to be a problem when static compilation is applied using compiler configuration, like is done in the Groovy7276 test.  When I added a test case there with `@CompileDynamic` on the class to cancel out the config and `@CompileStatic` on the method, the generated methods did not get static compilation.  But I think that is a more general issue with mixing compiler config with annotations and generated methods.

**Comment by eric-milles** [comment]
Also, there is some room for improvement in `org.codehaus.groovy.transform.sc.StaticCompilationVisitor#isStaticallyCompiled` and `org.codehaus.groovy.classgen.asm.sc.StaticTypesWriterController#updateStaticCompileFlag`.  An inner class may have an enclosing method that should take precedence over the outer class.  And the update method appears to repeat some logic that is or could be encompassed in the isser or the SC visitor.

**Pull request merged**
