### PR TITLE
GROOVY-9807: limit receiver replacement for implicit-this in inner class

### PR DESCRIPTION
**Pull request by eric-milles**
When user creates a method call expression, the default is for implicit
this to be true and this has caused a number of problems for transforms
when applied to inner class scenarios.  Only when the object expression
is truly "this" should it be rewritten to "Outer.this" when referencing
an outer class method.

https://issues.apache.org/jira/browse/GROOVY-9807

### CODE REVIEW

**Comment by danielsun1106** [comment]
GroovyCodeVisitorAdapter is for specific purpose, so how about making it AIC instead of standalone new class?

**Comment by eric-milles** [comment]
> `GroovyCodeVisitorAdapter` is for specific purpose, so how about making it AIC instead of standalone new class?

What is missing from `GroovyCodeVisitor` and `CodeVisitorSupport` is the ability to override select methods of interest and restrict traversal.  If I were to create a straight AIC of `GroovyCodeVisitor` in `InvocationWriter#isThis`, the method would be hundreds of lines long and the number of imports for the class would double.  This adapter is useful outside of this particular application -- in fact I imported the implementation from groovy-eclipse.

**Comment by eric-milles** [comment]
Any code that uses a sequence of `instanceof` checks to distinguish `ASTNode`/`Expression`/`Statement` types could instead leverage `GroovyCodeVisitorAdapter` and the visitor pattern for type dispatch.

**Comment by danielsun1106** [comment]
Merged. Thanks!

**Comment by paulk-asert** [comment]
Yep, I am happy with the `GroovyCodeVisitorAdapter` class but if we can think of a better name, I'd also be +1 for that.

**Pull request merged**
