### PR TITLE
GROOVY-4636: AST Browser does not show object initializer statements

### PR DESCRIPTION
**Pull request by jwagenleitner**

### CODE REVIEW

**Comment by paulk-asert** [comment]
+1, this looks good. Worth merging into 2_4_X before I cut the next release?

**Comment by jwagenleitner** [comment]
Thanks for reviewing Paul.  I don't think it's worth trying to merge into 2_4_X before the release since it's just a minor improvement and not worth the risk of introducing any problems.

**Comment by paulk-asert** [comment]
With this script:
```
import java.util.concurrent.ConcurrentLinkedQueue

class Test extends GroovyTestCase {
    void test() {
        def ti = new TestInterceptor()
        ti.matchAll()
        println ti.matchers
    }
}

trait Interceptor {
    final Collection<String> matchers = new ConcurrentLinkedQueue<>()
    void matchAll() {
        matchers << 'foo'
    }
}

class TestInterceptor implements Interceptor {
}
```
I get this error when attempting to view the AST:
```
General error during canonicalization: Cannot cast object 'org.codehaus.groovy.ast.stmt.ExpressionStatement@52ae4578[expression:org.codehaus.groovy.ast.expr.MethodCallExpression@4f0a6b91[object: org.codehaus.groovy.ast.expr.ClassExpression@519179d9[type: Interceptor$Trait$Helper] method: ConstantExpression[$init$] arguments: org.codehaus.groovy.ast.expr.ArgumentListExpression@4b1cfd47[org.codehaus.groovy.ast.expr.VariableExpression@6b39f4d9[variable: this]]]]' with class 'org.codehaus.groovy.ast.stmt.ExpressionStatement' to class 'org.codehaus.groovy.ast.stmt.BlockStatement'
```

**Comment by jwagenleitner** [comment]
Should be fixed by PR #477.

**Pull request closed without merging**
