### PR TITLE
Optimize generation of Groovydoc

### PR DESCRIPTION
**Pull request by melix**
There's a lot to say about Groovydoc, but worst of all, its performance is terrible. This PR is an attempt to fix part of it.

Before my changes: https://scans.gradle.com/s/msfs2nf5mqmxw (3m35s)
After my changes: https://scans.gradle.com/s/a7pi5g6bb7bbu (53s)

@paulk-asert I'm leaving the review/merge to you as I spent already too much time on this. Given the improvements, I wouldn't mind a backport to 2.5!

### CODE REVIEW

**Comment by graemerocher** [comment]
Nice! Performance of `groovydoc` definitely needs improvement

**Comment by danielsun1106** [comment]
+1

**Comment by melix** [comment]
Backported to 2.5.x and 2.6.x

**Comment by paulk-asert** [comment]
I did a quick review. All looks great.

**Pull request merged**
