### PR TITLE
If a converter is found, further process the result

### PR DESCRIPTION
**Pull request by jameskleeh**

### CODE REVIEW

**Comment by jameskleeh** [comment]
Should this line be using the generator instead?
 https://github.com/apache/groovy/blob/master/subprojects/groovy-json/src/main/java/groovy/json/StreamingJsonBuilder.java#L731

**Comment by jwagenleitner** [comment]
Yes I think that method was added fairly recently and was missed, the generator should replace all calls to `JsonOutput.toJson`.

**Comment by jwagenleitner** [comment]
Would like to know what you think about removing the `Object convert(Object)` method and just leave the `Object convert(Object,String)` method on the Converter, doesn't seem like both are needed as long as it documented that the key may be null.

**Comment by jameskleeh** [comment]
@jwagenleitner Makes sense to me

**Comment by jwagenleitner** [comment]
PR merged, thanks!

**Pull request closed without merging**
