### PR TITLE
GROOVY-10879: Additional DGM collectEntries variants

### PR DESCRIPTION
**Pull request by paulk-asert**

### CODE REVIEW

**Comment by daniellansun** [comment]
+1

**Comment by eric-milles** [comment]
That's a lot of new methods.  Any chance of splitting it up into separate PRs for each name so they can be reviewed separately?   new `collectEntries` variant seemed reasonable-ish.  But there are a lot more there to try and understand.  For me, producing a map always meant "collectEntries".  Not sure I agree with adding new names for making maps.

**Comment by paulk-asert** [comment]
There are 24 methods but it is basically:
4 types: Iterators, Iterables, arrays and Maps BY
2 options: supplied collector or new map BY
3 scenarios: change key and value, change key, change value

```
collectEntries(Iterator<E> self, Map<K, V> collector, Function<? super E, K> keyTransform, Function<? super E, V> valueTransform)
collectEntries(Iterator<E> self, Function<? super E, K> keyTransform, Function<? super E, V> valueTransform)
collectEntries(Iterable<E> self, Map<K, V> collector, Function<? super E, K> keyTransform, Function<? super E, V> valueTransform)
collectEntries(Iterable<E> self, Function<? super E, K> keyTransform, Function<? super E, V> valueTransform)
collectEntries(E[] self, Map<K, V> collector, Function<? super E, K> keyTransform, Function<? super E, V> valueTransform)
collectEntries(E[] self, Function<? super E, K> keyTransform, Function<? super E, V> valueTransform)
collectEntries(Map<X, Y> self, Map<K, V> collector, Function<? super X, K> keyTransform, Function<? super Y, V> valueTransform)
collectEntries(Map<X, Y> self, Function<? super X, K> keyTransform, Function<? super Y, V> valueTransform)
    
withCollectedValues(Iterator<K> keys, Map<K, V> collector, Function<? super K, V> valueTransform)
withCollectedValues(Iterator<K> keys, Function<? super K, V> valueTransform)
withCollectedValues(Iterable<K> keys, Map<K, V> collector, Function<? super K, V> valueTransform)
withCollectedValues(Iterable<K> keys, Function<? super K, V> valueTransform)
withCollectedValues(K[] keys, Map<K, V> collector, Function<? super K, V> valueTransform)
withCollectedValues(K[] keys, Function<? super K, V> valueTransform)
collectValues(Map<K, V> keys, Map<K, V> collector, Function<? super V, V> valueTransform)
collectValues(Map<K, V> keys, Function<? super V, V> valueTransform)
    
withCollectedKeys(Iterator<V> values, Map<K, V> collector, Function<? super V, K> keyTransform)
withCollectedKeys(Iterator<V> values, Function<? super V, K> keyTransform)
withCollectedKeys(Iterable<V> values, Map<K, V> collector, Function<? super V, K> keyTransform)
withCollectedKeys(Iterable<V> values, Function<? super V, K> keyTransform)
withCollectedKeys(V[] values, Map<K, V> collector, Function<? super V, K> keyTransform)
withCollectedKeys(V[] values, Function<? super V, K> keyTransform)
collectKeys(Map<K, V> keys, Map<K, V> collector, Function<? super K, K> keyTransform)
collectKeys(Map<K, V> keys, Function<? super K, K> keyTransform)
```

**Comment by daniellansun** [comment]
Merged. Thanks!

**Pull request merged**
